alias zrc="vim ~/.zshrc"
alias vrc="vim ~/.vimrc"
alias nrc="vim ~/.nanorc"
alias neo="vim ~/.config/neofetch/config.conf"
alias src="source ~/.zshrc"
alias home="cd ~/"
alias properties="vim ~/.termux/termux.properties"
alias qc=": > ~/.zsh_history && exit"
alias q="exit"
alias excode="echo $?"
alias bckp="tar -zcf /sdcard/termux-backup.tar.gz -C /data/data/com.termux/files ./home ./usr"
alias colo="vim ~/.termux/colors.properties"
alias headers="ls ~/../usr/include"
alias ls="exa -l -a"
alias cls="clear"
alias cdebug="clang -Wall -Wextra -std=c99 -g"
alias ccompile="clang -Wall -Wextra -std=c99"
alias revert="tar -zxf /sdcard/termux-backup.tar.gz -C /data/data/com.termux/files --recursive-unlink --preserve-permissions"
