
echo " "
echo -e " ████████████████  \e[1mWelcome to Termux!\e[0m"
echo " ██            ██"
echo -e " ██  ██        ██  \e[1mWiki:\e[0m   \e[4mhttps://wiki.termux.com\e[0m"
echo -e " ██  ██        ██  \e[1mGitter:\e[0m \e[4mhttps://gitter.im/termux/termux\e[0m"
echo -e " ██            ██  \e[1mSource:\e[0m \e[4mgithub.com/termux/termux-app\e[0m"
echo " ██            ██"
echo -e " ████████████████  \e[1mTermux version:\e[0m $TERMUX_VERSION"
echo " "
echo -e "                   \e[1mWorking with packages:\e[0m"
echo -e "                       \e[1mSearch:\e[0m pkg search <query>"
echo -e "                       \e[1mInstall:\e[0m pkg install <package>"
echo -e "                       \e[1mUpgrade:\e[0m pkg update && upgrade"
echo " "

echo -e "                   \e[1mSubscribing to additional repositories:\e[0m"
echo -e "                       \e[1mRoot:\e[0m pkg install root-repo"
echo -e "                       \e[1mX11:\e[0m pkg install x11-repo"
echo " "

echo "                   For fixing any apt repository issues, try"
echo "                   'termux-change-repo' command."
echo ""
echo -e "                   Report issues at \e[4mhttps://termux.dev/issues\e[0m"
echo ""